name: Generate Snake Animation

on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite rodar manualmente pela aba Actions
  workflow_dispatch:
  # Roda sempre que você der push na branch main
  push:
    branches:
      - main

# Permissão necessária para a Action escrever na branch "output"
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Gerar o SVG da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: EmilyPereiraRibeiroAcad
          # color_dots: 1º valor = casinha VAZIA (fundo dark do GitHub #161b22)
          # os outros 4 = níveis de contribuição, em tons de rosa 🎀
          outputs: |
                dist/snake-dark.svg?palette=github-dark&color_snake=#ff79c6&color_dots=#161b22,#5a1f3d,#a12d6b,#e83e8c,#ff79c6

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
